[project]
name = "model-serialization"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "onnx>=1.17.0",
    "tensorflow>=2.18.0",
    "tf2onnx>=1.16.1",
]
